/* eslint-disable @next/next/no-sync-scripts */
import './globals.css'
import { Cabin } from 'next/font/google'


const cabin = Cabin({ subsets: ['latin'] })

import Navbar from './components/Navbar'

export const metadata = {       
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className}>{children}
      
        <Navbar />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/datepicker.min.js"></script>
      </body>
    </html>
  )
}
